<a href="https://colab.research.google.com/github/rickiepark/MLQandAI/blob/main/supplementary/q10-random-sources/dropout.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 드롭아웃

In [1]:
import torch


class MLP(torch.nn.Module):
    def __init__(self, num_features, num_classes):
        super().__init__()

        self.all_layers = torch.nn.Sequential(
            torch.nn.Linear(num_features, 10),
            torch.nn.ReLU(),
            torch.nn.Dropout(0.5),

            # output layer
            torch.nn.Linear(10, num_classes),
        )

    def forward(self, x):
        logits = self.all_layers(x)
        return logits

In [2]:
torch.manual_seed(123)

model = MLP(num_features=5, num_classes=2)

## 훈련할 때 드롭아웃 적용하기

In [3]:
x = torch.tensor([1., 0.3, 2.4, -1.1, -0.8])

In [4]:
model(x)

tensor([ 0.1405, -0.1217], grad_fn=<ViewBackward0>)

In [5]:
model(x)

tensor([ 0.0446, -0.0222], grad_fn=<ViewBackward0>)

## 추론할 때 드롭아웃 제외하기

In [6]:
model.eval();

In [7]:
model(x)

tensor([-0.0458, -0.1777], grad_fn=<ViewBackward0>)

In [8]:
model(x)

tensor([-0.0458, -0.1777], grad_fn=<ViewBackward0>)

노트: 추론 시에는 그레이디언트를 추적하지 않도록 `torch.no_grad()`나 `torch.inference_mode()` 컨텍스트를 사용하는 것도 좋습니다. 추론할 때 `.eval()`이 드롭아웃을 끈다는 것을 보이기 위해 위에서는 사용하지 않았습니다.

In [9]:
with torch.inference_mode():
    print(model(x))

tensor([-0.0458, -0.1777])
