<a href="https://colab.research.google.com/github/rickiepark/MLQandAI/blob/main/supplementary/q10-random-sources/random-weights.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 랜덤한 가중치 초기화

### 랜덤 시드 사용하지 않는 경우

In [1]:
import torch


layer = torch.nn.Linear(2, 3)
print(layer.weight)

Parameter containing:
tensor([[-0.1558,  0.6908],
        [-0.6809, -0.0069],
        [-0.0577, -0.2206]], requires_grad=True)


In [2]:
layer = torch.nn.Linear(2, 3)
print(layer.weight)

Parameter containing:
tensor([[ 0.6107, -0.0511],
        [-0.4191,  0.5215],
        [-0.1921, -0.3824]], requires_grad=True)


### 랜덤 시드 사용하는 경우

In [3]:
torch.manual_seed(123)

layer = torch.nn.Linear(2, 3)
print(layer.weight)

Parameter containing:
tensor([[-0.2883,  0.0234],
        [-0.3512,  0.2667],
        [-0.6025,  0.5183]], requires_grad=True)


In [4]:
torch.manual_seed(123)

layer = torch.nn.Linear(2, 3)
print(layer.weight)

Parameter containing:
tensor([[-0.2883,  0.0234],
        [-0.3512,  0.2667],
        [-0.6025,  0.5183]], requires_grad=True)
